# Generated by Django 5.1.4 on 2025-01-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_imma', models.CharField(max_length=20, unique=True)),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=50)),
                ('kilometrage', models.IntegerField()),
                ('etat', models.BooleanField(default=True)),
                ('prix_location', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='voitures/')),
            ],
        ),
    ]
