# Generated by Django 5.1.4 on 2025-01-21 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_locataire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.locataire')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.voiture')),
            ],
        ),
    ]
